### ISSUE TITLE
ContainerBlock CopyTo IndexOutOfRangeException

### ISSUE THREAD

**Issue by ladeak** [xoofx/markdig#628]
When I call ToList() on a ContainerBlock (ListItemBlock) with a single item in it, I get a IndexOutOfRangeException.

Stacktrace:
```
   at System.Runtime.CompilerServices.CastHelpers.StelemRef(Array array, Int32 index, Object obj)
   at Markdig.Syntax.ContainerBlock.CopyTo(Block[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

This seems to be a regression since v28.1. I am still further looking into the detailts.

(.NET6, Blazor app)

**Comment by MihaZupan** [comment]
Caused by a typo here:
https://github.com/xoofx/markdig/blob/master/src/Markdig/Syntax/ContainerBlock.cs#L133

Should be `arrayIndex + i` instead of `arrayIndex + 1`.

As a temporary workaround, you can avoid the `CopyTo`.

```c#
var list = new List<Block>(container.Count);
for (int i = 0; i < list.Count; i++)
    list[i] = container[i];
```
